.travis.sh, .travis.yml, Makefile, src/Make.files
Recent changes had broken the build on ARM by adding more long double functions. These should be skipped on ARM, where double = long double.
This commit also adds Travis CI tests, which can be run automatically on every push to github. To do that, go to https://travis-ci.org/ and enable tests for the repository (it's free). Ideally, do this before merging (it will only run the tests for commits made after enabling it).
Here's the output from my fork (which has tests enabled): https://travis-ci.org/talex5/openlibm/builds/45933733
It does two builds on each commit, one on x86 and one cross-compiling to arm (which would detect the bug fixed above). On x86, it also runs the unit-tests. As the unit-tests currently fail on ARM I have disabled them, but if you set LOADER to `ld-linux-armhf.so.3` …
=> Fix build on ARM and add Travis tests

.travis.yml, Makefile
Would anyone be opposed to this? I get occasional build failures in Julia due to "unable to cp, file exists" or similar errors. This was probably triggered by a different change I made in one of Julia's makefiles, but that was fixing a different problem.
=> add -f flag to cp in install target

amd64/bsd_ieeefp.h, bsdsrc/b_exp.c, bsdsrc/b_tgamma.c, include/cdefs-compat.h, include/fpmath.h, src/e_scalb.c, src/e_scalbf.c, src/math_private.h, src/openlibm.h
Hi there,
I'm currently working on getting openlibm working in an alternative POSIX-like environment which I'm planning on releasing in a couple of months from now. It seems the code builds pretty well, though I needed to tweak it in a couple of places.
Attached are a couple of cleanups that are needed to get openlibm to build.
Ed
=> Portability fixes

src/k_exp.c, src/k_expf.c, src/openlibm.h, src/s_ccosh.c, src/s_ccoshf.c, src/s_cexp.c, src/s_cexpf.c, src/s_conj.c, src/s_conjf.c, src/s_conjl.c, src/s_cproj.c, src/s_cprojf.c, src/s_cprojl.c, src/s_csinh.c, src/s_csinhf.c, src/s_csqrt.c, src/s_csqrtf.c, src/s_csqrtl.c, src/s_ctanh.c, src/s_ctanhf.c
I am currently working on building openlibm against stock copies of
<math.h>, instead of the openlibm.h header. It seems that a C compliant
<math.h> header can be used as a drop-in replacement for openlibm.h,
with the exception that it lacks cpack*().
In FreeBSD SVN r275819 I patched up the math library by replacing
cpack*() by CMPLX*(). That way many functions become less tied to the
intrinsics of the math library. Make the same change to openlibm.
=> Change existing code to use CMPLX*() instead of cpack*() where possible.

ld128/e_lgammal_r.c, ld128/e_tgammal.c, ld80/Make.files, ld80/e_lgammal_r.c, ld80/e_tgammal.c, src/Make.files, src/e_lgammal.c, src/openlibm.h
Hi there,
I am currently working on porting openlibm to an environment where the global variable signgam is not available. signgam is only part of the X/Open System Interface, not the C standard.
The attached changes reduce the coupling against signgam, making it easier to build a copy of openlibm that does not depend on it. It fixes tgammal() to not modify signgam. In addition to that, it replaces lgammal() by a simple wrapper around lgammal_r(), similar to lgammaf_r() and lgamma_r().
Ed
=> Clean up handling of signgam

test/libm-test.c
There is no guarantee that the FP stack is preserved, and apparently
this no longer works with modern compilers. #55.
=> Remove floating point stack checks in tests

src/s_cbrtl.c
This would not build on i386 due to a missing include.
Namely nothing included bsd_ieeefp.h so it wouldn't build.
=> Fix build for x86 32 bit targets

Make.inc, Makefile, README.md, test/Makefile
This is rather basic. A clean is needed to get rid of artifacts from
previous runs with other architectures.
Note this requires PR #88 to work because without it x86 is broken.
Closes #89
=> Add support for cross compiling with `make ARCH=name`

Make.inc, README.md
With this patch I have been able to successfully compile Openlibm on OpenBSD 5.7 (x86_64) using the following command:
gmake GCC=egcc GXX=eg++ USEGCC=1 ARCH=x86_64
I had to install gcc 4.9 from ports, as Openlibm does not compile with the default compiler shipped with OpenBSD 5.7, which is gcc 4.2.1. Also, gnumake must be installed for this to work.
=> Update Make.inc to detect OpenBSD

Make.inc, test/Makefile
Debian's blhc (build log hardening check) reports dpkg-buildflags-missing CPPFLAGS 48 (of 223), CFLAGS 2 (of 177), LDFLAGS 2 (of 3) missing
=> Fix missing buildflags

ld128/e_lgammal_r.c, ld128/e_rem_pio2l.h, src/aarch64_fpmath.h, src/fpmath.h
CloudABI's C library (cloudlibc) used a stock version of OpenLibm for its math functions. I recently added support for another architecture, AArch64, which required me to make a couple of small changes to the sources.
The following changes make it possible to use a stock version of OpenLibm once more.
=> Make OpenLibm build on AArch64 (aka ARM64).

ld80/s_exp2l.c
This fixes the unresolved symbol __fpgetprec in libopenlibm.so.1.0 on i386
=> Add missing include to inline __fpgetprec on i386

.travis.sh, Makefile, test/Makefile
This patch adds a make check target that builds and runs the tests using the shared library.
This is a prerequisite for resolving issue #99.
=> Test shared library

Make.inc
I am going over the patches in the openlibm Debian package to see which ones are useful to integrate into upstream openlibm.
=> [WIP] More makefile improvements

.travis.sh, Make.inc, Makefile, test/Makefile
This sets the default optimization level to -O2 as discussed in issue #105. The optimization flag may be overriden with CFLAGS, which the canonical way in distributions such as Debian.
On a general note, please allow sufficient time to the openlibm team members to review before merging.
=> Set default optimization flag to -O2

Make.inc, test/libm-test.c
the `rint` functions (`lrint`, `nearbyint`) etc cause problems on ARM and power when compiled with optimisations. This disables optimisations for those functions, and enables them for all others. Also reenables a disable test.
=> work around optimisation bugs for rint

Make.inc, Makefile
Also, let the `prefix` be configurable from outside(e.g `make prefix=/path`) .
=> FreeBSD has different pkg-config dir: /usr/local/libdata/

Make.inc, include/openlibm_fenv_powerpc.h
Fixes #120
Do we want to push the changes to fenv upstream to FreeBSD?
=> fix ARCH variable for powerpc, and rearrange fenv.h union for endianness

i387/bsd_ieeefp.h
=> Fix fpgetprec and fpsetprec.

include/openlibm_fenv_amd64.h
This reverts commit 8b3b52067563a5a212a7fbacf360907fe2dc5e57.
This was causing dllexport-related errors on win64, as seen in https://ci.appveyor.com/project/StefanKarpinski/julia/build/1.0.13704/job/ldq0cqvw68h933hy. If there's another way to fix the clang warnings that doesn't break the windows build, it's worth trying.
=> Revert "Fix #35"

ld128/s_nanl.c, ld80/s_nanl.c, src/math_private.h, src/math_private_openbsd.h, src/s_exp2.c, src/s_nan.c
I currently have a small number of local changes that I need to apply on top of openlibm to properly integrate it into CloudABI's C library. It would be nice if I could get rid of them. ;-)
=> Upstream local modifications to openlibm.

i387/fenv.c, src/bsd_cdefs.h, src/types-compat.h
The first commit fixes a warning on Fedora rawhide with GCC6. But we should check that this works on Windows.
The second commit is just a cleanup.
=> More header fixes

Make.inc, bsdsrc/b_tgamma.c, include/openlibm_fenv.h, include/openlibm_fenv_arm.h
This has been made much easier since recent commits by the addition of src/aarch64_fpmath.h and enabling builds for powerpc.
Mostly copied verbatim from Edmund Grimley Evans' patch in [Debian bug #803206](https://bugs.debian.org/803206).
So far, it builds and passes tests.  I haven't tried building Julia with it yet,
=> WIP: Enable build on aarch64

amd64/bsd_asm.h, ld80/s_exp2l.c
It looks like we didn't substitute the name of the bsd_cdefs.h header
file in two source files when renaming it.
=> Update remaining references to bsd_cdefs.h to cdefs-compat.h.

Makefile
This creates the properly named/versioned shared libraries (e.g. `libopenlibm.2.1.dylib` on OSX, `libopenlibm.so.2.1` on Linux, and just `libopenlibm.dll` on Windows).
=> Version libopenlibm properly

include/openlibm_fenv_arm.h
Compiling on ARM fails due to missing __*_DECLS definitions. Other fenv headers have this included.
=> Include missing decls for ARM

Makefile
When building a cross-compile toolchain for a freestanding platform one may not
want to build and install dynamic loadables.
=> Split install into subtargets

Make.inc
~~Did this edit from a browser, still double-checking this actually works, so don't merge.~~
Tested locally, should be working.
=> Set optimization level only if not already overridden

.travis.yml, Make.inc, Makefile, aarch64/Make.files, aarch64/fenv.c, include/openlibm_fenv_arm.h, src/Make.files, test/Makefile
* Significantly cleanup `ARCH` handling.  Previously, behavior differed if the same value of `ARCH` was defined within `Make.inc` or defined on the command line.  This made me very sad.
* Fix `arm` floating-point status register code so that the tests actually work.
* Add testing for `ppc64le` and `arm` architectures on Travis through the magic of `binfmt-support` and `qemu`.
I would like to publicly thank @yuyichao for his help in debugging the arm code.
=> Fixup architecture woes

src/Make.files
Per discussion in #157, it is correct to enable these for aarch64.
=> Enable long double functions for aarch64

test/Makefile
FreeBSD needs the RPATH set in order to find the libraries when building the test programs.
=> Set the RPATH for the test binaries on FreeBSD

README.md, src/s_nan.c, test/Makefile
The same change ~~would likely be necessary on OpenBSD as well~~ should _not_ be applied on OpenBSD.
=> Allow building on DragonFly BSD

Make.inc
Type punning via unions in clang is not safe without `-fno-strict-aliasing`. See https://bugs.llvm.org//show_bug.cgi?id=31928.
=> enable -fno-strict-aliasing for clang

src/s_sincosl.c
Hi,
I found that the outputs from sincosl are reversed.
According to man(3), the second argument is sin and the third argument is cos.
Thanks.
=> Fix reversed outputs of sincosl

src/e_atan2.c
Incorporated from FreeBSD source tree: https://github.com/freebsd/freebsd/commit/b21ccf63f28a3a4692d8a31419e0a725a1b1a800. The original authorship has been preserved here. Commit message from upstream:
> As a component of atan2(y, x), the case of x == 1.0 is farmed out to
> atan(y). The current implementation of this comparison is vulnerable
> to signed integer underflow (that is, undefined behavior), and it's
> performed in a somewhat more complicated way than it need be. Change
> it to not be quite so cute, rather directly comparing the high/low
> bits of x to the specific IEEE-754 bit pattern that encodes 1.0.
>
> Note that while there are three different e_atan* files in the
> relevant directory, only this one needs fixing. e_atan2f.c already
> compares against the full bit pattern …
=> msun: signed overflow in atan2

Make.inc
I was trying to compile this on cygwin for a third party platform [cross] (none of the big 4).
It turns out the Make.inc sets AR static archiver and GCC assembler when in reality often an assembler/compiler will have a tool prefix, such as i686-x-gcc or in my case x86_64-elf-gcc and x86_64-elf-ar.
In my case compilation works:
TOOLPREFIX=x86_64-elf- CFLAGS="-D__ELF__ -Iinclude -I/home/bobbyjo/exa/libbasesupport/include -I/home/bobbyjo/exa/libbasesupport/include/basesupport" make USEGCC=1 ARCH=x86_64 libopenlibm.a
and I get a static library, woo!
ALTERNATIVELY you could check for CC and AR environment variables and only set when unset.
=> Consider:  Add TOOLPREFIX

README.md, appveyor.yml
This runs on my AppVeyor account to avoid using up the JuliaLang paid AV queue.
Closes #165.
=> Add Windows testing with AppVeyor

Make.inc
Optimization was disabled in dcc0d8da7400b68cb0b02c4605ce10fd605f3a1a.  This PR serves as a reminder to enable it again.
=> Enable optimization again for *int.c and *intf.c 

Make.inc, Makefile, include/openlibm_fenv.h, include/openlibm_fenv_s390.h, s390/Make.files, s390/fenv.c, src/fpmath.h, src/s390_fpmath.h
This is a s390(x) port with the following results
````
test/test-double
testing double (without inline functions)
Test suite completed:
1118 test cases plus 932 tests for exception flags executed.
All tests passed successfully.
test/test-float
testing float (without inline functions)
Failure: Test: yn (10, 2.0) == -129184.54220803928264
Result:
is:         -1.29184562500000000000e+05  -0x1.f8a09000000000000000p+16
should be:  -1.29184539062500000000e+05  -0x1.f8a08a00000000000000p+16
difference:  2.34375000000000000000e-02   0x1.80000000000000000000p-6
ulp       :  3.0000
max.ulp   :  1.0000
Test suite completed:
1101 test cases plus 923 tests for exception flags executed.
1 errors occurred.
````
=> Add s390(x) port

include/openlibm_math.h, src/s_fpclassify.c, src/s_isfinite.c, src/s_isinf.c, src/s_isnan.c, src/s_isnormal.c, src/s_nexttowardf.c, src/s_signbit.c
For some sad reason, gcc poisons LONG_DOUBLE in sreal.c. The identifier has been changed to OPENLIBM_LONG_DOUBLE
=> Fix compilation of gcc when using openlibm as system libm

src/cdefs-compat.h
The recent fixes for NetBSD caused a macro redefinition for `openlibm_weak_reference` when building with `ARCH=wasm32`.
Fix by connecting to the condition chain.
=> Fix weak reference macro redefinition in wasm32 target

src/cdefs-compat.h, src/s_cacos.c, src/s_cacosh.c, src/s_casin.c, src/s_casinh.c, src/s_catan.c, src/s_catanh.c, src/s_clog.c, src/s_cpow.c
__strong_alias is an ELF feature that is not available on Darwin/MachO.
We have openlibm_strong_reference to paper over these differences,
but we weren't using it consistently. In particular, we were still
using it to define long double -> double aliases on platforms where
these are the same type (e.g. aarch64). This didn't used to matter,
because the only such platform we supported was always Linux and
thus ELF. This patch fixes these instances thus fixing the build
on Apple Silicon.
=> Replace a few remaining __strong_reference uses

include/openlibm_defs.h, include/openlibm_fenv_amd64.h, include/openlibm_math.h, src/math_private.h
On x86_64, openlibm_fenv.h is silently coupled to openlibm_complex.h due to the inclusion of math_private.h inside of openlibm_fenv_amd64.h. The math_private.h header was included to gain access to the OLM_DLLEXPORT macro. However, this macro is redefined, since it is originally defined in openlibm_math.h. This inclusion also exposes math_private.h to public clients, which is undesirable.
Instead, a standalone header is created to contain the OLM_DLLEXPORT definition. This header is used included in the appropriate files. openlibm_fenv_amd64.h is no longer coupled to math_private.h.
Resolves #191
=> Refactor: OLM_DLLEXPORT definition now lives in a standalone header.

amd64/fenv.c
Win32 has been using a hack to switch the `fenv` functions from `static`
to `DLLEXPORT`, we apply that hack to all platforms that do not use a
host `fenv.h`.
=> Export `fenv` functions on all platforms

Make.inc, Makefile, src/Make.files
My previous Apple Silicon build went through, so I thought it already
worked, but it turns out it accidentally built an armv7 build instead.
This actually fixes the Apple Silicon build. One thing to note in
particular is that on Apple Silicong `long double` is the same as
`double` while on Linux `long double` is a 128 bit double-double
format.
=> Fix Apple Silicon build

amd64/fenv.c
The implementation of `fesetenv` cannot be portable, as the value of
`FE_DFL_ENV` differs between platforms. On FreeBSD, it is a actual
environment. With glibc however, it's a sentinel -1 handled in the
implementation of its floating point functions.
https://github.com/freebsd/freebsd/blob/a41d904f70e8e9e3c3062952b52f0845af0af738/lib/msun/x86/fenv.h#L97-L99
https://github.com/bminor/glibc/blob/acdcca72940e060270e4e54d9c0457398110f409/sysdeps/x86/fpu/bits/fenv.h#L96-L97
With openlibm based on FreeBSD's libm, it assumes `FE_DFL_ENV` to be an
actual environment. That assumption breaks using code that was compiled
against glibc, e.g., `libcuda`:
```
Thread 1 "julia-debug" received signal SIGSEGV, Segmentation fault.
0x00007ffff7b855d0 in fesetenv () from …
```
=> Revert "Export `fenv` functions on all platforms (#213)"

Make.inc
Fixes hard setting of toolchain functions.
Should not affect anyone.
Needed for cross compiling toolchain support.
=> don't alter toolchain vars if already provided

aarch64/fenv.c, powerpc/fenv.c
Ref https://github.com/JuliaLang/julia/issues/39462, https://github.com/JuliaLang/julia/pull/38466. Similarly to https://github.com/JuliaMath/openlibm/pull/219, this makes sure we don't export `fenv` routines on some additional platforms (being conservative here and only using those for which CUDA, which relies on this behavior, is available).
=> Make fenv methods static on additional platforms.

Make.inc, include/openlibm_math.h
Fixes missing declaration of `isinff` and invalid library creation due to the use of `ar` instead of `llvm-ar`.
=> Fix compilation errors on wasm32

src/e_hypotl.c
Fixes #224. Submitted upstream as https://github.com/freebsd/freebsd-src/pull/455.
=> Fix incorrect results in `hypotl` near underflow

src/s_cabs.c, src/s_ccos.c, src/s_csin.c, src/s_ctan.c
Similar to earlier pull request #210.
For some reason a few uses of `__strong_alias` were still left.
=> Replace remaining __strong_alias uses

bsdsrc/b_tgamma.c, src/e_acosh.c, src/e_atanh.c, src/e_cosh.c, src/e_exp.c, src/e_log.c, src/e_log10.c, src/e_log2.c, src/e_pow.c, src/e_sinh.c, src/s_asinh.c, src/s_erf.c, src/s_expm1.c, src/s_log1p.c, src/s_tanh.c
Some standard `long double` functions declared in `openlibm_math.h` do not have an implementation in `src`, so they are essentially missing on platforms where `long double` is a `double`.
Specifically, `acoshl`, `asinhl`, `atanhl`, `coshl`, `erfcl`, `erfl`, `expl`, `expm1l`, `log10l`, `log1pl`, `log2l`, `logl`, `powl`, `sinhl`, `tanhl`, and `tgammal`.
This PR uses the `openlibm_weak_reference()` mechanism to define them in terms of the `double`-based version. I'm not certain this is the best approach, but it seems worth a try. I have checked in a cross-compiling environment that all the target functions are exposed and functional.
=> Add missing aliases for 64-bit long double functions

src/cdefs-compat.h
In a case that I believe can only be hit for Clang i686-*-windows-gnu (AKA MinGW), symbols in asm need to be prefixed with `_`.  Fixes #237
=> prefix symbols with _ for 32-bit x86 Windows

.github/workflows/ci.yml
Ref #245
The presence of the `arch` variable is misleading, because it currently has no effect.
=> CI (Linux and macOS): Remove the `arch` variable, which currently has no effect

.github/workflows/ci.yml
=> CI (Windows): set `msys2 {0}` as the default shell for all Windows steps

Makefile
import libraries need to go in libdir (`/lib`), while dlls need to be on the PATH so need to be installed to shlibdir (`/bin`)
This hunk was overlooked from MINGW-packages' patch, noticed when opening msys2/MINGW-packages#9560
=> [Windows] install import library to libdir

src/aarch64_fpmath.h
include stdint.h to be sure that uint64_t can be used.
This header already had references to uint32_t, so I assumed it was safe to use those typedefs, but a compile error revealed it was not always.
=> Another Windows ARM64 fix

Make.inc
Bump version to 0.8 since we now have working CI now, with proper platform support, arm64 on win, and assorted fixes.
Bump the SOVERSION as well since we have some new exports and such.
=> Bump version to 0.8

Make.inc, Makefile, include/openlibm_fenv.h, include/openlibm_fenv_riscv.h, riscv64/Make.files, riscv64/fenv.c, src/fpmath.h, src/riscv_fpmath.h
Changes needed for riscv64 support have been added.
Code for openlibm_fenv_riscv.h, riscv_fpmath.h and fenv.c
was taken from https://github.com/freebsd/freebsd
=> Support for riscv64 architecture

i387/e_sqrt.S
As discussed in https://github.com/JuliaLang/julia/pull/43786, openlibm's sqrt function is incorrectly rounded for i387. IEEE requires correct rounding for these functions and LLVM relies on it. Fix that by setting the precision in the FPU control word (see e.g. e_ceil.S for similar FPU modifications).
Similar changes are not required for single precision because it does not suffer from the double rounding issue.
=> Correctly round double precision sqrt

docs/index.html
The self-referential link to http://www.openlibm.org is non-functional. Remove the `www`.
=> Remove non-working www subdomain from OpenLibm

src/s_sincos.c, src/s_sincosf.c
These files are derived from the original fdlibm sin/cos files. While we do already preserve that license notice in LICENSE.md (so there's no actual license compliance issue here), it's cleaner to have the copyright notice in the file as well, in case somebody copies the file out of the repo.
Fixes #264
=> Restore original fdlibm copyright on sincos files

include/openlibm_fenv.h, src/fpmath.h
Apple versions of GCC define __ppc__ instead of __powerpc__
Fixes #275
=> Fix Apple PowerPC build

Makefile, openlibm.pc.in
This patch makes the pkgconfig file respect prefix directory overrides.
=> build: fix pkgconfig cflags and libdir variables

Make.inc, Makefile, include/openlibm_fenv.h, include/openlibm_fenv_loongarch64.h, loongarch64/Make.files, loongarch64/fenv.c, src/fpmath.h, src/loongarch64_fpmath.h
Support for LoongArch64, a new ISA developed by Loongson Company which is already supported by glibc.
=> Support for loongarch64 architecture

CMakeLists.txt, README.md
I've also updated the README with instructions with directions on building static/shared library with CMake :)
Apart from CI, this should fix #289 .
=> Add support for building shared library with CMake

CMakeLists.txt, README.md
- Fixed cmake aarch64 build for macOS due to a mistake in `long double == double` size check, this should fix #292 .
- Apply the filtering out of C implementation if native implementation exists for static library builds as well.
- Default to building a shared library just like the GNU make build, and updated the README to reflect this.
=> Correct long double check in CMakeLists.txt and remove duplicate definitions for static library builds too

.github/workflows/ci.yml, .gitignore, Make.inc, Makefile, README.md
=> test: add target to gen coverage report

.github/workflows/cross.yml, Make.inc, README.md
Part of #290 
maybe next time/pr
- loongarch64
I tried installing the toolchain locally, but it doesn't compile properly yet. Need further attempts.
- Builds successfully, but tests fail.
I'll open an issue to track this: 
- mips64: https://github.com/JuliaMath/openlibm/actions/runs/7551712094/job/20559382618?pr=296
- mips64el: https://github.com/JuliaMath/openlibm/actions/runs/7551712094/job/20559382950?pr=296
=> CI: Setup cross build test

Make.inc, README.md
Modern clang works just fine, also llvm-gcc is nowhere to be found.
=> build: use clang to build wasm32

include/openlibm_fenv.h, include/openlibm_fenv_powerpc.h, src/fpmath.h
@ViralBShah This took forever :) Sorry for a ridiculous delay, it was forgotten.
Here are two tiny fixes:
1. Use a macro which includes `ppc64`, so that it is not left broken on macOS. (BTW, this still leaves out AIX, I believe?)
2. Make sure `__BYTE_ORDER__` is actually defined: AFAIK, it may not be the case with some old gcc versions, and those support C99, so it is relevant.
=> Minor fix-ups for Darwin PowerPC

amd64/e_fmod.S, amd64/e_fmodf.S, amd64/e_fmodl.S
This adds stack markings to the missing fmod .S files, otherwise the final libopenlibm object file gets marked with an executable stack.
Output when compiling from source on Gentoo Linux:
```
* QA Notice: The following files contain writable and executable sections
*  Files with such sections will not work properly (or at all!) on some
*  architectures/operating systems.  A bug should be filed at
*  https://bugs.gentoo.org/ to make sure the issue is fixed.
*  For more information, see:
*
*    https://wiki.gentoo.org/wiki/Hardened/GNU_stack_quickstart
*
*  Please include the following list of files in your report:
*  Note: Bugs should be filed for the respective maintainers
*  of the package in question and not hardened@gentoo.org.
* RWX --- --- usr/lib64/libopenlibm.so.4.0
```
=> Add stack markings for GNU to fmod assembly files

loongarch64/fenv.c, riscv64/fenv.c
I have no idea why previous versions compile on GitHub actions, but they don't on my loongarch64 machine, and there was also someone reported on aarch64 architecture #278 . Initializer of a struct should be a brace-enclosed list. Btw, my gcc version is 14.2.1, it seems that cross-compile gcc version in GitHub actions is old.
=> Fix fenv_t initializer

.github/workflows/cross.yml, Make.inc
ref: https://github.com/libuv/libuv/pull/4630
> The active environment is selected via the `MSYSTEM` environment variable
> https://www.msys2.org/docs/environments/
=> ci: Fix clang build and Update qemu

Make.inc
See individual commit messages for descriptions and motivations of changes. We should tag a new patch version after this is merged.
=> Fixes for building on AArch64 with Clang

.github/workflows/cross-loongarch64.yml
- The `gcc-loongarch64-linux-gnu` package seems not to exist on Ubuntu 24.04, so install `gcc-14-loongarch64-linux-gnu` manually.
See: https://github.com/JuliaMath/openlibm/actions/runs/12617775708/job/35160409682?pr=313#step:3:55
- Manual specification of `CC, AR` during compilation and testing
=> ci: add loongarch64

.github/workflows/ci.yml
Coverage hasn't been properly submitted in a long time. The issue as reported by the CI job is that we need a token, so I've added one in the repository settings and this commit just tells the action to use it.
=> Add Codecov token to CI

include/openlibm_fenv.h, include/openlibm_fenv_aarch64.h, include/openlibm_fenv_arm.h
AArch64 has two 64bit regs, AArch32 only has one.
The high 32 bits of both registers are reserved, so we only need to save the low 32 bits and pack them into a uint64.
- copy `aarch64/fenv.h` from FreeBSD
https://github.com/freebsd/freebsd-src/blob/de1aa3dab23c06fec962a14da3e7b4755c5880cf/lib/msun/aarch64/fenv.h
Fix #278
=> aarch64/fenv: fix `fenv_t`

.github/workflows/ci.yml, .gitignore, Makefile
Close #290, replace #298 
TODO: remove old tests
=> ci: test with openlibm-test

include/openlibm_fenv_powerpc.h, include/openlibm_fenv_s390.h
`__uint32_t` and `__BEGIN_DECLS` aren't standard so slight modifications are needed when they aren't provided by the libc
=> Musl compatibility fixes for s390 and powerpc

CMakeLists.txt
On cmake-4.1.0, when openlibm is included as a subdirectory, it causes an error:
Setting CMAKE_PROJECT_VERSION can also fix this issue, but I don't really prefer doing so.
```
CMake Error at openlibm/CMakeLists.txt:569 (string):
string sub-command REPLACE requires at least four arguments.
```
=> Fix cmake error for 4.x
